server:
  port: 8899
spring:
  application:
    name: my-password
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${SPRING_DATASOURCE_URL_HOST:127.0.0.1}:3306/${SPRING_DATASOURCE_URL_DB:my-password}?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&&serverTimezone=Hongkong
    username: root
    password: root
    hikari:
      connection-timeout: 0
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 28740000
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: Abc@12345678
    timeout: 300s
    lettuce:
      pool:
        max-active: 8
        max-idle: 30
        max-wait: 10s
        min-idle: 10
springfox:
  documentation:
    swagger-ui:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'loggers'
  endpoint:
    health:
      show-details: always
logging:
  file:
    path: /logs/${spring.application.name}
  level:
    com.zkdj.management.external.ManagementStorageService: info
    com.querydsl.jpa.impl.JPAQuery: debug
custom:
  account:
    first-error-account-lock-time: 3 #账户密码输入错误 锁定时间 单位：分钟
    first-error-account-error-count: 5 #账户密码输入错误 最大次数
    second-error-account-lock-time: 30 #账户密码输入错误 锁定时间 单位：分钟
    second-error-account-error-count: 10 #账户密码输入错误 最大次数
    third-error-account-lock-time: 3 #账户密码输入错误 锁定时间 单位：小时
    third-error-account-error-count: 15 #账户密码输入错误 最大次数
    private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALKgNoZuAZ9b5uUF/CIpVZmhfNV+Z2NkDcWB0FeYI6yZydQc73chF0q70aICCf1Mv4T+68RsuVN33hAcmP3wKanXRAAniVNNj0l56AiNbyiw8ab3Npq20DQ1oxf3gchV52l5IhIuvbjrV+YkWoJtLBOlU5FLQffimKLlG2r3dDb3AgMBAAECgYADrZvh0cMTynsrLR/ffjVmh/Y/mS481DMaZY1qOFZHuBT5Wq0tqU9G+S4cZWlaP2nULcGiFlEMoHPApi4aUIczEMVdlx9v/R5uFzF9Er0nqYgehvm5Y7QQtayiC7FWLU5blTPcqwudAFhl03SDbQsoB9Lp8sqVJXTsdZrxMcNKxQJBAOoupOADtVsD3hF1ZX42bul2vKiBEWuXQwFR6VcdwnxwaQDeD0f5p0BoOISIPkvw5LebhFWCv9brJwC5MB/fg60CQQDDRIX2zKNwJC7ezjYg6k21sJbSUCrWR/Hq7uA3+7Zu2NAuAjXCMf3B0HCp5+obPXIWCmxvVrTEDXzuE7trdFmzAkAXqYrjT7yda7CelvwgWqOuV18Mr63w7yHIGly3frxOEpWpjsaAgUtTCLTdP178EWUq4D3o3gNAVhZkzlF8hvspAkEAhb2uH46jtpAhxhro+fxgwzuy4VNlM6TNLgL0cYOmvR8k3w5Gcb65tgCk2cptDsE0HaKACHYTk2BFm+7J5FwpfwJAGyzfQiaeVKwse9UP89MjdUWN/xzzv9N55Mr6oEGN3sj3Bj4wVwsl25w5+LZLTajxpNcEb9M95cmo/Xf5PkojnQ==
    publish-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCyoDaGbgGfW+blBfwiKVWZoXzVfmdjZA3FgdBXmCOsmcnUHO93IRdKu9GiAgn9TL+E/uvEbLlTd94QHJj98Cmp10QAJ4lTTY9JeegIjW8osPGm9zaattA0NaMX94HIVedpeSISLr2461fmJFqCbSwTpVORS0H34pii5Rtq93Q29wIDAQAB
  file:
    profiles-picture-path: /file/profilesPicture
  secret-key:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8ubLkqx0Re/T8Q6qAWKP+p4uCKBZmEHvuWYK0jmk0zx3c9B+QPZsKvnzYc+r2q5OXsV2vjiKDWYtDyRDulq0zTjF8bnGxiQoXBzCLIwwVkfwRSeC5vOLxL7BN1pWbuIkfsksatnRC4Pq5yYoEZCSzS0ZBAR7ORy5Wa6yHLzoqNwIDAQAB
    private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBALy5suSrHRF79PxDqoBYo/6ni4IoFmYQe+5ZgrSOaTTPHdz0H5A9mwq+fNhz6vark5exXa+OIoNZi0PJEO6WrTNOMXxucbGJChcHMIsjDBWR/BFJ4Lm84vEvsE3WlZu4iR+ySxq2dELg+rnJigRkJLNLRkEBHs5HLlZrrIcvOio3AgMBAAECgYBTy7Q1uhBnEf3eAIF1CWaPjH7yJLCFUu5kD1RsrQrjis78q1xUZDYyGBBA339FVTtsUDGD4H1Miva9+0nMVhTCffBtzraBn/Yqd381uUaYuP86ChVMRED3qeGpAnjL33CnC7IQMMMURzc5A7USVdpdOakNIBhMcSTbZkHE7VZLYQJBAPHfENrpVwqs/kLA2xvVPoIrFzwaBUi5W+Kk1biqy0Y6/WtCbwmEp9PdJNbwWVIi4DgVfQdgcw/Fs1HqjdWLIrECQQDHv+Pxc9orGv844i+SIjE2wTYTqKY9qNctqTyXacTJpIfH1D86yQuvB7WGjoe48X7dVFX+/fL4aCYB2C+sncVnAkBxXyyoX92DzIi1w24wwqi1HPucGVpGt1Ohjb/7+lqjxbzJjO89F+gOv8an1SsY++37e98KGSR1zSZ7jCUFZl1RAkEAryKDA++06Lhp8AD4/qK2DbEH7eKfp05DJAjPVF5rKPT2C/H/YlZlxRf4Q7ryKuiqd/p6z/DuuHfwYwueeTV3nwJAUWTEpPNOGKnp+3LzATBEmaoZJ2yK2OPCYIPetEytQr0rNjgDpZessNFkCERKdsqLTHY1JXRUgsb1+y+h9Fzqnw==

